# -*- coding: utf-8 -*-
"""Anjula_Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTe_UDtUtXzeX8QioGURtHgIacLif2ya
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import ADASYN



url = "https://raw.githubusercontent.com/AnjulaMehto/Sampling_Assignment/main/Creditcard_data.csv"
df = pd.read_csv(url)

print("Original Class Distribution:")
print(df['Class'].value_counts())

X = df.drop("Class", axis=1)
y = df["Class"]

scaler = StandardScaler()
X = scaler.fit_transform(X)



sampling_methods = {
    "Sampling1_RandomOver": RandomOverSampler(),
    "Sampling2_SMOTE": SMOTE(),
    "Sampling3_RandomUnder": RandomUnderSampler(),
    "Sampling4_SMOTEENN": SMOTEENN(),
    "Sampling5_ADASYN": ADASYN()
}



models = {
    "M1_Logistic": LogisticRegression(max_iter=2000),
    "M2_DecisionTree": DecisionTreeClassifier(),
    "M3_RandomForest": RandomForestClassifier(),
    "M4_NaiveBayes": GaussianNB(),
    "M5_KNN": KNeighborsClassifier()
}



results = pd.DataFrame(index=models.keys(), columns=sampling_methods.keys())

for s_name, sampler in sampling_methods.items():

    X_res, y_res = sampler.fit_resample(X, y)

    X_train, X_test, y_train, y_test = train_test_split(
        X_res, y_res, test_size=0.2, random_state=42
    )

    for m_name, model in models.items():
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds) * 100
        results.loc[m_name, s_name] = round(acc, 2)


print("\nAccuracy Table (%)\n")
print(results)


best_value = results.astype(float).max().max()
best_location = results.astype(float).stack().idxmax()

print("\nBest Accuracy:", best_value)
print("Best Model:", best_location[0])
print("Best Sampling:", best_location[1])

"""**Visualizations**"""

import matplotlib.pyplot as plt

results = results.astype(float)


avg_sampling = results.mean()

plt.figure()
avg_sampling.plot(kind="bar")
plt.title("Average Accuracy per Sampling Technique")
plt.ylabel("Accuracy (%)")
plt.show()



for model in results.index:
    plt.figure()
    results.loc[model].plot(kind="bar")
    plt.title(f"Accuracy for {model}")
    plt.ylabel("Accuracy (%)")
    plt.show()


for sample in results.columns:
    plt.figure()
    results[sample].plot(kind="bar")
    plt.title(f"{sample} across Models")
    plt.ylabel("Accuracy (%)")
    plt.show()


plt.figure()
results.plot(kind="bar")
plt.title("All Models vs Sampling Techniques")
plt.ylabel("Accuracy (%)")
plt.show()

plt.figure()
plt.imshow(results.values)
plt.xticks(range(len(results.columns)), results.columns, rotation=45)
plt.yticks(range(len(results.index)), results.index)
plt.colorbar()
plt.title("Accuracy Heatmap (Models vs Sampling)")
plt.show()

avg_sampling = results.mean()

plt.figure()
avg_sampling.plot(kind='bar')
plt.title("Average Accuracy per Sampling Technique")
plt.ylabel("Accuracy (%)")
plt.show()

for model in results.index:
    plt.figure()
    results.loc[model].plot(kind='bar')
    plt.title(f"Accuracy for {model}")
    plt.ylabel("Accuracy (%)")
    plt.show()

plt.figure()
results.plot(kind='bar')
plt.title("All Models vs Sampling Techniques")
plt.ylabel("Accuracy (%)")
plt.show()

